### ISSUE TITLE
Exam question: Partial Credit and Strange Autograder Errors? EDIT**

### ISSUE THREAD

**Issue by bdhack23** [comp426-2022-fall/assignments#22]
#### Question: ~~Will there be partial credit for the final? It looks like I'm passing portions of parts, but my score does not go up. Or am I not reading the autograder correctly? In the screenshot, it looks like maybe I got one part of task 1 correct, but another part incorrect. But my score never seemed to improve from before when I had no parts correct.~~ FIXED 

Also, will there still be partial credit for stuff that did not pass the autograder? Like perhaps if we were close to passing the test but not completely correct?

Autograder is also giving me strange errors about unhandled error events in Task 1 and claiming that "math.add" in Task 2 is not a function. ~~Task 3 autograder is also claiming I have no index.html file when I very clearly do.~~FIXED I'll add screenshots of the autograder:
<img width="448" alt="task1 1" src="https://user-images.githubusercontent.com/77807845/206343634-ff1eeac0-dabc-41fc-ace8-3879003acd5b.PNG">
<img width="381" alt="test2 0" src="https://user-images.githubusercontent.com/77807845/206343651-cd3a6e0b-7450-4abe-ab57-45055b314ff1.PNG">

#### Link to documentation: 
math.js: https://mathjs.org/docs/getting_started.html
Unhandled Error Event: https://peterthaleikis.com/posts/how-to-fix-throw-er-unhandled-error-event.html

#### What should be happening?: ~~I feel like I should be getting partial credit but I am not, as the score never seems to go up with fixing parts of my code.~~ FIXED 
Autograder for Task 1 is also giving me strange errors about unhandled error events and Task 2 autograder claiming that "math.add" is not a function, ~~as well as Task 3 autograder claiming that index.html doesn't exist when I can definitely see that it does.~~

#### Why do you think the autograder is failing? (BE SPECIFIC) ~~Not sure, perhaps something is wrong with my computer or maybe my files are not very compatible with the autograder.~~ Perhaps something in my package.json is making it where the autograder is having a difficult time understanding some of my code(I have had technical difficulties with it in the past, such as with the midterm.) ~~I've looked at documentation, google, etc for hours and have made zero progress.~~ Any advice is welcome. Here is a screenshot my package.json(without anything in "test"), if that helps:
<img width="905" alt="packagejson" src="https://user-images.githubusercontent.com/77807845/206345475-0342fa5f-010b-43bd-b7d2-ed2ca1eca8f9.PNG">

**Comment by jdmar3** [comment]
So there is no real way for things that don't pass the check to be determined to be "almost passing" because they are all just testing whether the supplied inputs produce the expected outputs. For there to be partial credit, we would have to be hand evaluating 560+ directories full of code individually and I think that it should be relatively clear why that is not possible to do given that one instructor has 72 hours to turn compile and post grades for the course. It's not a thing.

With the `math.js` issue, the intent was not to have you use the math.js package, but to just write a script called `math.js`  with an add function in it that gets exported using CommonJS methods. `math.add()` in the evaluation scripts refers to _your_ math.js script, not any external package. That's what is in the README.

None of the errors you are getting are strange. They are just errors.

For the `index.html` errors, make sure that you are actually referencing the correct relative path and not either a 1) nonexistent path, or 2) an absolute path.
